### ISSUE TITLE
Trivia Game - Courtney Seitz (Project1)

### ISSUE THREAD

**Issue by Courtney-Seitz** [ga-dc/project1-gallery#1]
Link to repo: https://github.com/CourtneySeitz/Trivia/tree/master
Link to deployed app: http://courtneyseitz.github.io/Trivia/

Things you'd like specific feedback on: 
- Arranging my JS/jQuery properly; I realized some nesting affected how my code functioned, or maybe it was my code structure? I wasn't sure if it mattered much where functions were nested, in some cases it seemed it mattered, such as the anonymous function nesting (obviously). 
- A better way to do this with more Javascript/jQuery vice HTML? I know there is a way, but I'm not comfortable enough with JS to go there...yet! OR, if it's better to do this with little JS and mostly HTML?
- How to correctly loop back through the questions once the quiz ended, which was something I wanted to do but kept getting painted in a corner and stuck on how to do it without breaking everything and making the quiz progression fail completely.
- Any CSS feedback.
- I noticed that originally I had tried to use checkboxes, but those hindered the JS functions in some way, or maybe I wasn't approaching the solution correctly, so I switched to radio buttons. Any known reason for this?

Any HTML feedback.

Thanks!!!

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 2

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in?

## Technical Requirements: 1

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 2

> Did you follow code style guidance and best practices covered, such as spacing, modularity, and semantic naming? Did you comment your code?

~~**You have to keep your indentation consistent, and semantically name your variables.** No more of this `var t` business. This is **not** something you can retroactively add to your code. You must be doing it from the start.~~

EDIT: Sorry! I included this by accident from another evaluation.

Great job commenting your code!

## Creativity/Interface: 2

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

My inline code comments: https://github.com/CourtneySeitz/Trivia/pull/2/files

Nice job, Courtney! Particularly good job with having clean and well-commented code.

My only real qualms with this app is that I wish your questions were generated using JS, rather than hardcoded HTML. That would actually likely have answered some of your other questions, like looping back to the original question.

For example:

``` js
var questions = [
  {
    prompt: "What color is a banana?",
    choices: ["Yellow", "Blue", "Purple", "Pink"]
  },
  {
    prompt: "What kind of food is a banana?",
    choices: ["Fruit", "Pizza", "Mammal", "Mineral"]
  }
]

questions.forEach(function(question, index){
  var html = "<div>";
  var correctAnswer = question.choices[0];
  question.choices = shuffle(question.choices);
  html += "<h2>" + question.prompt + "</h2>";
  html += "<ul>";
  question.choices.forEach(function(choice){
    html += "<li>";
    html += "<input type='radio' question-number='" + index + "' value='" + choice + "'/>";
    html += choice;
    html += "</li>";
  });
  html += "</ul>";
  html += "</div>";
  $("#playArea").html(html);
});

$("input[type=radio]").on("click", function(){
  var element = $(this);
  var questionNumber = element.attr("question-number");
  var question = questions[questionNumber];
  if(element.val() === question.answer){
    alert("Correct!");
  }
});
```

My guess about the checkboxes is they're used for when you can select multiple answers for a question, whereas radio buttons let you select only one answer.

**Comment by RobertAKARobin** [comment]
Oops! I accidentally included a bit from another evaluation. See my edit above!

**Comment by Courtney-Seitz** [comment]
Thanks for the feedback! I actually realized knee-deep in that I should have incorporated the questions within JavaScript vice HTML, then just carried on anyway. When I go back and work on it I will approach it that way, but I honestly just wasn't completely comfortable stepping out and using JS so heavily (it terrifies me a bit) from scratch after spending so much time doing this the HTML way. Hindsight! Thanks again!
