### ISSUE TITLE
JG - The Game of War

### ISSUE THREAD

**Issue by wombatdev** [ga-dc/project1-gallery#18]
Link to repo: https://github.com/wombatdev/the-game-of-war
Link to deployed app: http://wombatdev.github.io/the-game-of-war/

Things you'd like specific feedback on:
Animation quality, war event function (I don't understand how it works, got it from Robin)
Generally, I think my code is poorly organized, poorly commented, not DRY, unreadable. Disappointing.

```
Comfort: JS/jquery - 5/5
         Animations/CSS - 3/5
Completeness: 4/5
```

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 2

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in (detailed above)?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 2

> Did you follow code style guidance and best practices covered in class, such as spacing, modularity, and semantic naming? Did you comment your code?

## Creativity/Interface: 2

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

Nice job, James! My inline comments are here:

https://github.com/wombatdev/the-game-of-war/pull/1/files

I think your code is good! You do have rather a lot of it, but that seems to be mostly because you're generous with whitespace and comments -- which is fine.

Now that you've had more familiarity with object-oriented programming, I'd recommend organizing your code in objects. For example:

```
var card = {
  flip: function(){
  },
  click: function(){
  }
}
```

...or use constructors if you're feeling crafty.

Yeah, the chaining thing is something that took a while to figure out. Consider this:

``` js
function sayHi(){
  alert("Hi");
}
setTimeout(function(){
  sayHi();
}, 1000);
```

You'd expect "Hi" to be alerted after 1 second.

Here's a way of getting 3 asynchronous functions to run in order:

``` js
goFirst();

function goFirst(){
  setTimeout(function(){
    alert("first");
    goSecond();
  }, 1000);
}
function goSecond(){
  setTimeout(function(){
    alert("second");
    goThird();
  }, 1000);
}
function goThird(){
  setTimeout(function(){
    alert("third");
  }, 1000);
}
```

That works, but the functions are all global variables, and it seems a little heavy-handed. Here's another way:

``` js
var functionNumber = 0;
var functions = [
  function(){
    setTimeout(function(){
      alert("first");
      functionNumber += 1;
      functions[functionNumber]();
    }, 1000);
  },
  function(){
    setTimeout(function(){
      alert("second");
      functionNumber += 1;
      functions[functionNumber]();
    }, 1000);
  },
  function(){
    setTimeout(function(){
      alert("third");
    }, 1000);
  }
]
functions[functionNumber]();
```

Notice all the repeating lines with `functionNumber`. We can DRY things up by putting those lines in a `next` function:

``` js
var functionNumber = -1;
var functions = [
  function(){
    setTimeout(function(){
      alert("first");
      next();
    }, 1000);
  },
  function(){
    setTimeout(function(){
      alert("second");
      next();
    }, 1000);
  },
  function(){
    setTimeout(function(){
      alert("third");
    }, 1000);
  }
]

next();
function next(){
  functionNumber += 1;
  functions[functionNumber]();
}
```

That's almost everything. Now we'll just make this method re-usable:

``` js
var functions = [
  function(next){
    setTimeout(function(){
      alert("first");
      next();
    }, 1000);
  },
  function(next){
    setTimeout(function(){
      alert("second");
      next();
    }, 1000);
  },
  function(next){
    setTimeout(function(){
      alert("third");
    }, 1000);
  }
]

function chainFunctions(functions){
  var functionNumber = -1;
  next();
  function next(){
    functionNumber += 1;
    functions[functionNumber](next);
  }
}
```
