### ISSUE TITLE
Shakespeare Trivia Game

### ISSUE THREAD

**Issue by EvanSanderson** [ga-dc/project1-gallery#31]
Link to repo: https://github.com/EvanSanderson/Trivia_Game
Link to deployed app: https://evansanderson.github.io/Trivia_Game/

Things you'd like specific feedback on:
How to refine the aFade function, how to shorten the dang thing down, and how to avoid using quite so many global variables

**Comment by nayana487** [comment]
Total: 10/12

Project Workflow:
2/3 - Nice job with the user stories here. You're very detailed. In the future, it'd be great to have some wireframes done before you write any code so you have a better sense from the start of how the app should look.

Technical Requirements:
3/3 - You've definitely gone above what was taught in class and implemented a lot of functionality in your app and used methods we hadn't even taught. 

Code Quality:
2/3 - It would be better practice to separate your code into appropriate folders instead of having a bunch of files under the main folder. That is, you should have a css and js folder. Also, more comments would have been helpful. 

Creativity
3/3 -  This was definitely a great interface and works very well with the goals you set out in your user stories. 

Your questions:

aFade function: I have to think a little more on this, but that array makes me think there's probably a way to implement the .each method, but since you want differing rates at which the fades appear, it makes sense that this would be a little bit longer. 

global variables: When you're writing something like this: var modal = $("#myModal"); it's just as easy to write out in the local function so there's not much point in taking up global space. 

shorten down: I think for the amount of functionality you have, the length here isn't too bad. One thing I would suggest is perhaps finding ways to combine functionality and not using global variables at all unless there is a compelling reason to do so.
