### ISSUE TITLE
Dilmurod Bukharov- PROJECT-4

### ISSUE THREAD

**Issue by dilmurodb** [ga-dc/project1-gallery#446]
Link to repo: https://github.com/dilmurodb/project-4
Link to deployed app: https://dilmurodb.github.io/project-4/

Things you'd like specific feedback on:

**Comment by mrrogercampbell** [comment]
Hey the game looks good. 

Few changes I'd like to see before I mark this as complete:

1. Fix the background image so that it spans the entire page
1. Fix your readme, no reason to have everything as a head `#` if you just want plan text you can type it with out markdown syntax in front of it. 

For now I am marking this as incomplete. Resubmission will be due 1/6/20

**Comment by dcartist** [comment]
Good job!
<img src="https://www.reactiongifs.us/wp-content/uploads/2017/09/Brilliant-Americas-got-Talent.gif"/>
