### ISSUE TITLE
Concentration Game - Gandy Young

### ISSUE THREAD

**Issue by gandyland** [ga-dc/project1-gallery#7]
Link to repo: https://github.com/gandyland/github.io-Concentration_Memory
Link to deployed app: http://gandyland.github.io/github.io-Concentration_Memory/

Things you'd like specific feedback on: I spent almost all my time on the Javascript so I'd like to know of any way to make that better. Either with readability or making it more concise. It functions exactly how I'd like it too but I haven't added any thing too complex to it yet.

**Comment by RobertAKARobin** [comment]
# Project Feedback + Evaluation

| Score | Expectations |
| --- | --- |
| 0 | Incomplete |
| 1 | Progressing |
| 2 | Performing |
| 3 | Excelling |

## Project Workflow: 1

> Did you complete the user stories, wireframes, task tracking, and/or ERDs, as specified above? Did you use source control as expected for the phase of the program you’re in?

## Technical Requirements: 2

> Did you deliver a project that met all the technical requirements? Given what the class has covered so far, did you build something that was reasonably complex?

## Code Quality: 2

> Did you follow code style guidance and best practices covered, such as spacing, modularity, and semantic naming? Did you comment your code?

## Creativity/Interface: 2

> Is your user interface easy to use and understand? Does it make sense for the problem you're solving? Does your interface demonstrate creative design?

## Overall: 2

Nice job, Gandy! See my comments at https://github.com/gandyland/github.io-Concentration_Memory/pull/1

**Comment by RobertAKARobin** [comment]
I did notice you and several other students relying heavily on this tutorial:

https://www.developphp.com/video/JavaScript/Memory-Game-Programming-Tutorial

Not a huge deal early on, but it means my comments aren't necessarily very helpful since the code was written somewhere else. Next time, I'd recommend reading through the tutorial, translating their code into pseudocode, closing the tutorial, and re-creating the functioning code from their pseudocode.
